server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: root
    password: Welcome_1
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
        show-sql: true
  main: 
    web-application-type: servlet
